sudo: required
services:
  - docker

before_install:
  - docker build -t jond02/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jond02/react-test npm test -- --coverage

after_success:
  - docker build -t jond02/multi-client ./client
  - docker build -t jond02/multi-nginx ./nginx
  - docker build -t jond02/multi-api ./api
  - docker build -t jond02/multi-worker ./worker
  # push images to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jond02/multi-client
  - docker push jond02/multi-nginx
  - docker push jond02/multi-api
  - docker push jond02/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-multi-udemy"
  env: "DockerMultiUdemy-env"
  bucket_name: "elasticbeanstalk-us-west-2-736338261372"
  bucket_path: "docker-multi-udemy"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"